---
- hosts: all
  become: true
  vars:
   companyName: MSS
   location: US
  tasks:
   - name: Install Apache HTTP Server
     yum: 
      name: httpd
      state: present
   - name: Start the Apache HTTP Server
     service:
       name: httpd
       state: started
   - name: Copy index.html
     template:
     src: index.html
     dest: /var/www/html/index.html
...