- hosts: all
  become: true
  tasks:
  - name: Install HttpServer in RedHat Linux Host
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "RedHat"
  - name: Install HttpServer in Ubuntu Linux Host
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

